#!/bin/bash

### This script regenerates the packaged html templates, copies any needed files
### (read: config files) to their proper place, and packages the turtl XPI file.
###
### Note that this script is meant to be run in the top-level addon folder, not
### not in the scripts/ folder.

# ------------------------------------------------------------------------------
# config section
# ------------------------------------------------------------------------------
# path to cfx
CFX=../../../addon-sdk-1.14/bin/cfx
# tmp dir for generating package
TMP=/tmp/turtl-package
# the resulting XPI file (*must* be the same as what cfx xpi produces)
XPI=turtl.xpi

nogen=$1

if [ "$nogen" != "--skip-tpl" ]; then
	# generate templates
	echo -n "Regenerating templates so we have the freshest versions..."
	./scripts/generate-templates
	echo "done."
fi

# package the addon
echo "Packaging addon (via cfx)."
$CFX xpi > /dev/null

# grab the app dir
pushd data/app/ > /dev/null
APPDIR=`pwd -P`
popd > /dev/null

# create/enter our temp dir
mkdir -p $TMP
rm -rf $TMP/*
EXTDIR=`realpath .`
pushd $TMP/ > /dev/null

echo -n "Upacking addon to make modifications..."
unzip $EXTDIR/$XPI > /dev/null
echo "done."

echo "  - copying live config over local"
cp $EXTDIR/lib/config.live.js resources/turtl/lib/config.js
rm -f resources/turtl/data/app

echo "  - symlinking app subfolder"
ln -s $APPDIR resources/turtl/data/app

echo "  - setting applicable permissions"
chmod 644 -R resources/addon-sdk
chmod 644 bootstrap.js

echo -n "Repackaging..."
zip -r turtl . -x *.git* > /dev/null
echo "done."

mv turtl.zip $EXTDIR/$XPI
popd > /dev/null

echo "Clearing tmp dir ($TMP/)"
rm -rf $TMP

echo "Complete. Created fully-packaged file: $XPI."

